name: presence
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lucide_icons: ^0.257.0
  expandable_search_bar: ^0.0.2
  animation_search_bar: ^0.0.10
  animated_search_bar: ^2.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-VariableFont_wght.ttf

    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/SourceCodePro-VariableFont_wght.ttf

    - family: AlumniSans
      fonts:
        - asset: assets/fonts/AlumniSans-Regular.ttf

    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf

    - family: PoetsenOne
      fonts:
        - asset: assets/fonts/PoetsenOne-Regular.ttf
